version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: resolvomt
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resolvomt
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./api
    image: resolvomt-backend:latest 
    container_name: resolvomt-api
    ports:
      - "8081:8080" 
    depends_on:
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/resolvomt
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data: